language: java
jdk: openjdk8
sudo: required
services: docker
install: true
apt_packages:
  - docker-ce
  - bash
script:
  - ./gradlew clean test
  - ./mvnw clean test
cache:
  directories:
    - ~/.docker
    - ~/.gradle
    - ~/.m2
  packages: true
